# Generated by Django 4.0.4 on 2022-06-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaning',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
